/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'agonz' at '10/7/17 3:17 PM' with Gradle 2.14.1
 *
 * @author agonz, @date 10/7/17 3:17 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
